# Generated by Django 3.0.7 on 2020-06-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('virus', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('tipo', 'virus')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(choices=[('V', 'visualização'), ('I', 'inserção'), ('A', 'alteração'), ('R', 'remoção')], max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.OneToOneField(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='laboratorio.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Usa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Exame')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Servico')),
            ],
            options={
                'unique_together': {('id_servico', 'id_exame')},
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='exames',
            field=models.ManyToManyField(through='laboratorio.Usa', to='laboratorio.Exame'),
        ),
        migrations.CreateModel(
            name='Pode_fazer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, to='laboratorio.Perfil')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.PROTECT, to='laboratorio.Servico')),
            ],
            options={
                'unique_together': {('id_perfil', 'id_servico')},
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='servicos',
            field=models.ManyToManyField(through='laboratorio.Pode_fazer', to='laboratorio.Servico'),
        ),
        migrations.CreateModel(
            name='Acessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, to='laboratorio.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='laboratorio.Pessoa')),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('id_tutor', models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorio.Usuario')),
                ('perfis', models.ManyToManyField(through='laboratorio.Acessa', to='laboratorio.Perfil')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servico',
            unique_together={('nome', 'classe')},
        ),
        migrations.AddField(
            model_name='acessa',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='laboratorio.Usuario'),
        ),
        migrations.CreateModel(
            name='Utilizou',
            fields=[
                ('id_utilizacao', models.IntegerField(db_column='id_utilizacao', primary_key=True, serialize=False)),
                ('data_utilizacao', models.DateTimeField()),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Exame')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Servico')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Usuario')),
            ],
            options={
                'unique_together': {('id_utilizacao', 'id_usuario', 'data_utilizacao')},
            },
        ),
        migrations.CreateModel(
            name='Tutelamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Perfil')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Servico')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, related_name='id_atutor', to='laboratorio.Usuario')),
                ('id_tutorado', models.ForeignKey(db_column='id_tutorado', on_delete=django.db.models.deletion.CASCADE, related_name='id_btutorado', to='laboratorio.Usuario')),
            ],
            options={
                'unique_together': {('id_tutor', 'id_tutorado', 'id_perfil', 'id_servico')},
            },
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(blank=True, null=True)),
                ('codigo_amostra', models.CharField(blank=True, max_length=255, null=True)),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Exame')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Paciente')),
            ],
            options={
                'unique_together': {('id_paciente', 'id_exame', 'data_realizacao')},
            },
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_amostra', models.CharField(max_length=255)),
                ('metodo_coleta', models.CharField(max_length=255)),
                ('tipo_material', models.CharField(max_length=255)),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Exame')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Paciente')),
            ],
            options={
                'unique_together': {('id_paciente', 'id_exame', 'codigo_amostra')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='acessa',
            unique_together={('id_usuario', 'id_perfil')},
        ),
    ]
