# Generated by Django 3.0.7 on 2020-06-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_labjef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, unique=True)),
                ('virus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('classe', models.CharField(choices=[('V', 'visuzalição'), ('I', 'inserção'), ('A', 'alteração'), ('R', 'remoção')], max_length=1, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_labjef.Exame')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_labjef.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Pode_fazer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_labjef.Perfil')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_labjef.Servico')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usa',
            constraint=models.UniqueConstraint(fields=('id_servico', 'id_exame'), name='unique_servico_exame'),
        ),
        migrations.AddConstraint(
            model_name='pode_fazer',
            constraint=models.UniqueConstraint(fields=('id_perfil', 'id_servico'), name='unique_perfil_servico'),
        ),
    ]
