# Generated by Django 3.0.7 on 2020-06-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_labjef', '0002_auto_20200623_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='servicos',
            field=models.ManyToManyField(through='site_labjef.Pode_fazer', to='site_labjef.Servico'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exames',
            field=models.ManyToManyField(through='site_labjef.Usa', to='site_labjef.Exame'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='site_labjef.Pessoa'),
        ),
    ]
